runtime: nodejs10
entrypoint: npm run start:prod
handlers:
  - url: /images
    static_dir: dist/public/images
    http_headers:
      Access-Control-Allow-Origin: '*'
# runtime: nodejs
# env: flex
# entrypoint: npm run start:prod
# manual_scaling:
#   instances: 1
# network:
#   session_affinity: true
env_variables:
  WEBSOCKET_PORT: 65080
  SQL_HOST: ruby.db.elephantsql.com
  SQL_USER: xdstzbvq
  SQL_PASSWORD: KnnbbTF-Zudk-OrqTvNgHh0I8da79xSq
  SQL_DATABASE: xdstzbvq