runtime: nodejs10
entrypoint: npm run start:prod
env_variables:
  WEBSOCKET_PORT: 65080
  SQL_HOST: ruby.db.elephantsql.com
  SQL_USER: xdstzbvq
  SQL_PASSWORD: KnnbbTF-Zudk-OrqTvNgHh0I8da79xSq
  SQL_DATABASE: xdstzbvq
handlers:
  - url: /images
    static_dir: dist/public/images
    http_headers:
      Access-Control-Allow-Origin: '*'